[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python start_wrapper.py"
healthcheckPath = "/healthz"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
PYTHON_VERSION = "3.11"
PORT = "8080"