[build]
builder = "nixpacks"
buildCommand = "python -m pip install --upgrade pip && python -m pip install -r requirements.txt"
watchPatterns = ["**/*.py", "requirements.txt", "railway.toml"]

[deploy]
numReplicas = 1
startCommand = "python start_wrapper.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"
restartPolicyMaxRetries = 10
region = "us-west1"

[env]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PYTHON_VERSION = "3.11"
